package pageObjects;

import com.microsoft.playwright.Locator;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.options.AriaRole;
import lombok.Getter;

@Getter
public class ChatBotPage {
    private final Locator btnCloseChat;
    private final Locator btnStartMessageRU;
    private final Locator btnStartMessageENG;
    private final Locator btnCreateChannelRU;
    private final Locator btnCreateChannelENG;
    private final Locator btnExpandCompaseChat;
    private final Locator btnSearchUser;
    private final Locator btnUseUser;
    private final Locator btnTextChat;
    private final Locator btnSendMess;
    private final Locator btnMenuM;
    private final Locator btnCopyM;
    private final Locator btnForwardM;
    private final Locator btnEditM;
    private final Locator btnDeleteM;
    private final Locator btnSelectM;
    private final Locator btnReactionM;
    private final Locator btnReactionC;
    private final Locator wnwCopied;
    private final Locator wnwForwardU;
    private final Locator wnwForwardT;
    private final Locator wnwForwardI;
    private final Locator wnwEditI;
    private final Locator wnwEditS;
    private final Locator wnwDeleteY;
    private final Locator btnSelectD;
    private final Locator wnwSelectT;
    private final Locator wnwDeleteC;
    private final Locator btnEnterNameChan;
    private final Locator btnSearchUserChan;
    private final Locator btnNextCreateChan;
    private final Locator wnwCreateChan;
    private final Locator wnwCreatedChan;
    private final Locator btnUserMenuChan;
    private final Locator btnInfoChan;
    private final Locator btnAdduser;
    private final Locator btnRemoveMember;
    private final Locator btnMakeAdmin;
    private final Locator btnReMakeAdmin;
    private final Locator btnUserName;
    private final Locator btnAddMember;
    private final Locator btnMenuChan;
    private final Locator btnLeaveChan;
    private final Locator btnTakeUserChanQA;
    private final Locator btnTakeUserChanPP;
    private final Locator wnwLeavedChanC;
    private final Locator btnPreviousChan;
    private final Locator btnEditChan;
    private final Locator btnBackToChan;
    private final Locator wnwInfoChan;
    private final Locator wnwNewNameChan;
    private final Locator btnSaveNameChan;
    private final Locator wnwRenamedChan;
    private final Locator btnAddMemberInChan;
    private final Locator btnUserNameInChan;
    private final Locator wnwTakeUserInChan;
    private final Locator btnButtonAddMembChan;

    public ChatBotPage(Page page) {
        this.btnCloseChat = page.locator(".cursor-pointer").first();
        this.btnStartMessageRU = page.getByText("Написать сообщение");
        this.btnStartMessageENG = page.getByText("Start message");
        this.btnCreateChannelRU = page.getByText("Добавить канал");
        this.btnCreateChannelENG = page.getByText("Add channel");
        this.btnExpandCompaseChat = page.locator(".header-main-height > svg:nth-child(2)");
        this.btnSearchUser = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div/div[1]/input");
        this.btnUseUser = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div/div[2]");
        this.btnTextChat = page.locator("//*[@id=\"messageInput\"]");
        this.btnSendMess = page.locator("#aibot-chat-wrapper").getByRole(AriaRole.BUTTON);
        this.btnMenuM = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div/div/div/div");
        this.btnCopyM = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[2]/div[1]");
        this.wnwCopied = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/div");
        this.btnForwardM = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[2]/div[2]");
        this.wnwForwardU = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[3]/div/div/div[2]/div/input");
        this.wnwForwardT = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[3]/div/div/div[2]/div/div[2]");
        this.wnwForwardI = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[2]");
        this.btnEditM = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[2]/div[4]");
        this.wnwEditI = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[2]");
        this.wnwEditS = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div[1]/div/div/div/div[2]");
        this.btnDeleteM = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[2]/div[6]");
        this.wnwDeleteY = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[3]/div/div[3]/button[2]");
        this.wnwDeleteC = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/div");
        this.btnSelectM = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[2]/div[6]");
        this.btnSelectD = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[2]/div/svg");
        this.wnwSelectT = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div[1]");
        this.btnReactionM = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[2]/div[2]/div[1]/div[2]");
        this.btnReactionC = page.locator(".message-reactions");
        this.btnEnterNameChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[1]/div/div[1]/div[2]/div[3]/div/div/div[2]/input");
        this.btnSearchUserChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[1]/div/div[1]/div[2]/div[3]/div/div/div[3]/div[1]/input");
        this.btnTakeUserChanQA = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[1]/div/div[1]/div[2]/div[3]/div/div/div[3]/div[1]/div[2]/div");
        this.btnTakeUserChanPP = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[1]/div/div[1]/div[2]/div[3]/div/div/div[3]/div[3]/div");
        this.btnNextCreateChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[1]/div/div[1]/div[2]/div[3]/div/div/div[4]/button[2]");
        this.wnwCreateChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/div");
        this.wnwCreatedChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[1]/div/div[3]/div");
        this.btnInfoChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/header/div/div[2]");
        this.btnUserMenuChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[1]/div[3]/div[2]/div[3]/div[2]/div/a");
        this.btnAdduser = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[1]/div[3]/div[2]/div[1]");
        this.btnRemoveMember = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[1]/div[3]/div[2]/div[3]/div[2]/div/div/div[2]");
        this.btnMakeAdmin = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[1]/div[3]/div[2]/div[3]/div[2]/div/div/div[1]");
        this.btnReMakeAdmin = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[1]/div[3]/div[2]/div[3]/div[2]/div/div/div[1]");
        this.btnUserName = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[2]/div/div/div[2]/div/input");
        this.btnAddMember = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[2]/div/div/div[3]/button[2]");
        this.btnMenuChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[1]/div[2]/button[3]");
        this.btnLeaveChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[1]/div[3]/div[2]/div[3]/div/div");
        this.wnwLeavedChanC = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div[2]/div/p");
        this.btnPreviousChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[1]/div/div[1]/div[2]/div[1]/div[1]/div[2]/div");
        this.btnEditChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/header/div/a");
        this.wnwNewNameChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[3]/div/div/div[2]/input");
        this.btnSaveNameChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[3]/div/div/div[3]/button[2]");
        this.btnBackToChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/header/div/div");
        this.wnwInfoChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/header/div/p");
        this.wnwRenamedChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/div");
        this.btnAddMemberInChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[1]/div[3]/div[2]/div[1]");
        this.btnUserNameInChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[2]/div/div/div[2]/div/input");
        this.wnwTakeUserInChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[2]/div/div/div[2]/div/div[2]/div");
        this.btnButtonAddMembChan = page.locator("//*[@id=\"aibot-chat-wrapper\"]/div/div/main/div[2]/section[2]/div/div[1]/div/div[2]/div/div/div[3]/button[2]");
    }
}